# Generated by Django 4.2 on 2023-05-30 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_parentsblog_teacherblog'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentsblog',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentblog',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teacherblog',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
